## Q0: (0 point) 
- Please install Anaconda on your own PC or the PC in the lab. (Download link: https://www.anaconda.com/download/ )
- Please install related python3 packages: numpy, scikit-learn, jupyter (pip3 install numpy, scikit-learn, jupyter)

## Q1: (100 point) 
Use NumPy module to define and operation the following operations on matrices and vectors. Please readme the following example and answer sub-questions 1-5 in jupyter notebook.

### Example for Q1
#### Question: 
- Calculate the matrix multiplication between random matrix A (shape 4x3) and random matrix B (shape 3x5)

In [2]:
# Answer to example
import numpy as np
# 1. Generate random matrix A and B
a = np.random.random(size=(4, 3))
b = np.random.random(size=(3, 5))
# 2. Execute matrix multiplication and assign the result to matrix C
c = np.matmul(a, b)
# 3. Print the shape and value of C
print(c.shape)
print(c)

(4, 5)
[[1.00247798 1.10184928 0.67061532 0.56105896 0.52841903]
 [0.87989242 0.28397698 0.749823   0.71663057 0.93446911]
 [1.21006639 0.8776346  1.05677394 0.84379458 0.7417476 ]
 [0.5225502  0.39876739 0.41888925 0.35366792 0.35517999]]


### (1) Define NumPy Array
#### Question: 
- Use NumPy to define the following matrix A and vector b, then print A and b
$$
 A = 
 \begin{bmatrix}
   1 & 2 & 3 & 3\\
   4 & 5 & 6 & 1\\
   7 & 8 & 9 & 4
  \end{bmatrix},
   b =
 \begin{bmatrix}
   7 \\
   4 \\
   1 \\
  \end{bmatrix}
$$


In [3]:
# Answer to sub-question 1
import numpy as np

A = np.array([[1,2,3,3],[4,5,6,1],[7,8,9,4]])
b = np.array([[7],[4],[1]])
print(A)
print(b)

[[1 2 3 3]
 [4 5 6 1]
 [7 8 9 4]]
[[7]
 [4]
 [1]]


### (2) Basic Mathematical Operation
#### Question:  
- Mulitply scalar3 and substract scalar 6 to each element in A, then print the new result matrix.

In [4]:
# Answer to sub-question 2

print(A*3-6)


[[-3  0  3  3]
 [ 6  9 12 -3]
 [15 18 21  6]]


### (3) Broadcast Mechanism
#### Question:
- Use the broadcast mechanism in NumPy to add b to **each row** of the matrix A, then print the new result matrix.

In [5]:
# Answer to sub-question 3
print(A+b)

[[ 8  9 10 10]
 [ 8  9 10  5]
 [ 8  9 10  5]]


### (4) Dimension Manipulation Operation
#### Question: 
- (Slice) Get the first and the third column of the Matrix A to construct a new matrix, then print it.
- (Split) Split the Matrix A to three row vectors, then print them.

In [6]:
# Answer to sub-question 4
print(A[:,0:2])
print(np.split(A,3))

[[1 2]
 [4 5]
 [7 8]]
[array([[1, 2, 3, 3]]), array([[4, 5, 6, 1]]), array([[7, 8, 9, 4]])]


### (5) Matrix Operation
#### Question:
- Execute SVD decompositon to the matrix A, then print the results (unitary matrix and singular value vector).

In [7]:
# Answer to sub-question 5
U,sigma,VT = np.linalg.svd(A)
print(U)
print(sigma)

[[-0.24531292 -0.87032483 -0.42703192]
 [-0.50037185  0.49095298 -0.71315719]
 [-0.83033101 -0.03872808  0.55592316]]
[17.4426792   2.45260916  0.85886587]
